<?php

namespace CvBundle\Repository;

/**
 * domaine_activiteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class domaine_activiteRepository extends \Doctrine\ORM\EntityRepository
{
}
