offre:
    resource: "@OffreBundle/Controller/"
    type:     annotation
    prefix:   /

entity:
    resource: "@EntityBundle/Controller/"
    type:     annotation
    prefix:   /



app:
    resource: '@AppBundle/Controller/'
    type: annotation
