worktn:
    resource: "@WorktnBundle/Controller/"
    type:     annotation
    prefix:   /

forum:
    resource: "@ForumBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
