<?php

namespace Entity\EntityBundle\Repository;

/**
 * OffreEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploiRepository extends \Doctrine\ORM\EntityRepository
{
}
