<?php

namespace ForumBundle\Repository;

/**
 * publication_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class publication_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
