<?php

namespace worktnBundle\Repository;

/**
 * abonnementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonnementRepository extends \Doctrine\ORM\EntityRepository
{
}
