<?php

namespace worktnBundle\Repository;

/**
 * abonnement_domaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class abonnement_domaineRepository extends \Doctrine\ORM\EntityRepository
{
}
