<?php

namespace worktnBundle\Repository;

/**
 * offre_emploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class offre_emploiRepository extends \Doctrine\ORM\EntityRepository
{
}
