<?php

namespace worktnBundle\Repository;

/**
 * session_candidatureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class session_candidatureRepository extends \Doctrine\ORM\EntityRepository
{
}
