<?php

namespace worktnBundle\Repository;

/**
 * sous_domaineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class sous_domaineRepository extends \Doctrine\ORM\EntityRepository
{
}
