<?php

namespace worktnBundle\Repository;

/**
 * utilisateur_profilRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class utilisateur_profilRepository extends \Doctrine\ORM\EntityRepository
{
}
