<?php

namespace EntityBundle\Repository;

/**
 * DomaineActiviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DomaineActiviteRepository extends \Doctrine\ORM\EntityRepository
{
}
