<?php

namespace EntityBundle\Repository;

/**
 * idPublicationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class idPublicationRepository extends \Doctrine\ORM\EntityRepository
{
}
