<?php

namespace EntityBundle\Repository;

/**
 * OffreEmploiRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OffreEmploiRepository extends \Doctrine\ORM\EntityRepository
{
    public function getListeOffreByIdRecruteur($id){

        $query = $this->createQueryBuilder('p')
            ->where('p.idRecruteur = ?1')
            ->setParameter(1, $id)
            ->getQuery();
        return $results = $query->getResult();
    }
}
