<?php

namespace EntityBundle\Repository;

/**
 * Publication_utilisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Publication_utilisateurRepository extends \Doctrine\ORM\EntityRepository
{
}
